name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Backend setup
      - name: Install dependencies for backend
        working-directory: server
        run: timeout 300 npm install --legacy-peer-deps --ignore-scripts

      - name: Run ESLint for backend
        working-directory: server
        run: npx eslint . --ext .js,.jsx || echo "Lint warnings/errors ignored"

      - name: Run backend tests
        working-directory: server
        run: npm test

      # Frontend setup
      - name: Install dependencies for frontend
        working-directory: client
        run: timeout 300 npm install --legacy-peer-deps --ignore-scripts

      - name: Run ESLint for frontend
        working-directory: client
        run: npx eslint . --ext .js,.jsx || echo "Lint warnings/errors ignored"

      - name: Run Stylelint for frontend
        working-directory: client
        run: npx stylelint "**/*.css" || echo "Stylelint warnings/errors ignored"

      - name: Run frontend tests
        working-directory: client
        run: npm test

      - name: Build frontend
        working-directory: client
        run: npm run build
