name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Sets an overall timeout for the job

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Backend setup and health check
      - name: Install dependencies for backend
        working-directory: server
        run: timeout 300 npm install  # Times out after 5 minutes if install hangs

      - name: Start Backend for Health Check
        working-directory: server
        run: |
          nohup npm start &             # Start backend in the background
          sleep 10                      # Wait 10 seconds to ensure the backend starts successfully
          pkill -f "node"               # Kill the backend process to exit gracefully

      # Frontend setup and health check
      - name: Install dependencies for frontend
        working-directory: client
        run: timeout 300 npm install  # Times out after 5 minutes if install hangs

      - name: Build and Start Frontend for Health Check
        working-directory: client
        run: |
          npm run build                # Builds the frontend
          nohup npm start &            # Start frontend in the background
          sleep 10                     # Wait 10 seconds to ensure the frontend starts successfully
          pkill -f "node"              # Kill the frontend process to exit gracefully

      - name: Deploy (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Add your deployment command or script here"
