name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Sets an overall timeout for the job

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Global Jest installation to avoid permission issues
      - name: Install Jest globally
        run: npm install -g jest

      # Backend setup, ESLint, and tests
      - name: Install dependencies for backend
        working-directory: server
        run: timeout 300 npm install --legacy-peer-deps

      - name: Run ESLint for backend
        working-directory: server
        run: npx eslint . --fix

      - name: Run backend tests
        working-directory: server
        run: npm test

      # Frontend setup, ESLint, and tests
      - name: Install dependencies for frontend
        working-directory: client
        run: timeout 300 npm install --legacy-peer-deps

      - name: Run ESLint for frontend
        working-directory: client
        run: npx eslint . --ext .js,.jsx --max-warnings=0

      - name: Run frontend tests
        working-directory: client
        run: npm test

      # Build Frontend
      - name: Build frontend
        working-directory: client
        run: npm run build  # Builds the frontend for production

      # Deployment (Optional)
      - name: Deploy (Optional)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Add your deployment command or script here"
